framework:
    messenger:
        transports:
            util:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                exchange: { name: 'gateway.util' }
                queues:
                  gateway.util: ~
            mailer_dispatch:
              dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
              options:
                exchange: { name: 'gateway.email' }
                queues:
                  gateway.email.dispatch: ~

        routing:
            'App\Message\SendEmailMessage': mailer_dispatch
            'App\Message\RecalculateBookRatingMessage': util
            'App\Message\CacheFeedPostMessage': util
            'App\Message\RemoveFeedPostFromCacheMessage': util
