Book:
  type: object
  config:
    fields:
      id: "Int!"
      title: "String!"
      author: "String!"
      genres: "[String]"
      pageCount: "Int!"
      coverUrl: "String"
      description: "String"
      rating: "Float"
      num_ratings: "Int"
      visibility: "BookVisibilityEnum!"
      reviews:
        type: "[FeedPost]!"
        args:
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\BookResolver::resolveBookReviews", args, value)'

BookSourceEnum:
  type: enum
  config:
    values:
      SYSTEM: "system"
      USER: "user"

BookVisibilityEnum:
  type: enum
  config:
    values:
      PUBLIC: "public"
      PRIVATE: "private"

CreateBookInput:
  type: input-object
  config:
    fields:
      title: "String!"
      author: "String!"
      genres: "[String]"
      pageCount: "Int!"
      coverUrl: "String"
      description: "String"
      visibility: "BookVisibilityEnum!"
