FeedPost:
  type: object
  config:
    fields:
      id: "Int!"
      user: "User!"
      log: "ReadLog"
      text: "String"
      type: "FeedPostTypeEnum!"
      createdAt: "DateTimeImmutable!"
      likeCount:
        type: "Int!"
        resolve: '@=query("App\\GraphQL\\Resolver\\FeedPostLikeResolver::resolvePostLikeCount", value)'
      likes:
        type: "[FeedPostLike]!"
        args:
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\FeedPostLikeResolver::resolvePostLikes", args, value)'
      comments:
        type: "[CommentThread]!"
        args:
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\CommentResolver::resolvePostComments", args, value)'

FeedPostTypeEnum:
  type: enum
  config:
    values:
      REVIEW: "review"
      FINISHED: "finished"
      TEXT: "text"

FeedPostLike:
  type: object
  config:
    fields:
      id: "Int!"
      user: "User!"
