Mutation:
  type: object
  config:
    fields:
      follow:
        type: "Boolean!"
        args:
          followedUserId: "Int!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\FollowMutation::follow", args)'
      unfollow:
        type: "Boolean!"
        args:
          unfollowedUserId: "Int!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\FollowMutation::unfollow", args)'