Mutation:
  type: object
  config:
    fields:
      follow:
        type: "Boolean!"
        args:
          followedUserId: "Int!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\FollowMutation::follow", args)'
      unfollow:
        type: "Boolean!"
        args:
          unfollowedUserId: "Int!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\FollowMutation::unfollow", args)'
      createReadLogFromExistingBook:
        type: "ReadLog!"
        args:
          bookId: "Int!"
          readLogInput: "CreateReadLogInput!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\ReadLogMutation::createReadLogFromExistingBook", args)'
      createReadLogFromNewBook:
        type: "ReadLog!"
        args:
          book: "CreateBookInput!"
          readLogInput: "CreateReadLogInput!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\ReadLogMutation::createReadLogFromNewBook", args)'
      createReadLogPageUpdate:
        type: "ReadLog!"
        args:
          pageUpdateInput: "CreateReadLogPageUpdateInput!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\ReadLogMutation::createReadLogPageUpdate", args)'
      deleteReadLogPageUpdate:
        type: "Boolean!"
        args:
          pageUpdateId: "Int!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\ReadLogMutation::deleteReadLogPageUpdate", args)'
      updateReadLog:
        type: "ReadLog!"
        args:
          updateReadLogInput: "UpdateReadLogInput!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\ReadLogMutation::updateReadLog", args)'
