Mutation:
  type: object
  config:
    fields:
      follow:
        type: "Boolean!"
        args:
          followedUserId: "Int!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\FollowMutation::follow", args)'
      unfollow:
        type: "Boolean!"
        args:
          unfollowedUserId: "Int!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\FollowMutation::unfollow", args)'
      createReadLogFromExistingBook:
        type: "ReadLog!"
        args:
          bookId: "Int!"
          readLogInput: "CreateReadLogInput!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\ReadLogMutation::createReadLogFromExistingBook", args)'
      createReadLogFromNewBook:
        type: "ReadLog!"
        args:
          book: "CreateBookInput!"
          readLogInput: "CreateReadLogInput!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\ReadLogMutation::createReadLogFromNewBook", args)'
      updateReadLogPage:
        type: "ReadLog!"
        args:
          pageUpdateInput: "CreateReadLogPageUpdateInput!"
        resolve: '@=mutation("App\\GraphQL\\Mutation\\ReadLogMutation::createReadLogPageUpdate", args)'
