Query:
  type: object
  config:
    fields:
      book:
        type: "Book"
        args:
          id: "Int!"
        resolve: '@=query("App\\GraphQL\\Resolver\\BookResolver::resolveBook", args)'
      readLog:
        type: "ReadLog"
        args:
          id: "Int!"
        resolve: '@=query("App\\GraphQL\\Resolver\\ReadLogResolver::readLog", args)'
      recommendBooks:
        type: "[Book]"
        args:
          query: "String!"
        resolve: '@=query("App\\GraphQL\\Resolver\\RecommendationResolver::recommendBooks", args)'
      user:
        type: "User!"
        args:
          id: "Int!"
        resolve: '@=query("App\\GraphQL\\Resolver\\UserResolver::user", args)'
      me:
        type: "User!"
        resolve: '@=query("App\\GraphQL\\Resolver\\UserResolver::me", args)'
      searchUsers:
        type: "[User]!"
        args:
          query: "String!"
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\UserResolver::searchUsers", args)'
      searchBooks:
        type: "[Book]!"
        args:
          query: "String!"
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\BookResolver::searchBooks", args)'
      feed:
        type: "[FeedPost]!"
        args:
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\FeedResolver::resolveFeed", args)'
