ReadLog:
  type: object
  config:
    fields:
      id: "Int!"
      book: "Book!"
      user: "User!"
      currentPage: "Int!"
      rating: "Float"
      review: "String"
      status: "ReadLogStatusEnum!"
      createdAt: "DateTimeImmutable!"
      updatedAt: "DateTimeImmutable"
      finishedAt: "DateTimeImmutable"
      pageUpdates:
        type: "[ReadLogPageUpdate]!"
        args:
          limit: "Int"
          offset: "Int"
          sortField: "ReadLogPageUpdateSortableFieldsEnum"
          sortDirection: "SortDirectionEnum"
        resolve: '@=query("App\\GraphQL\\Resolver\\ReadLogResolver::resolvePageUpdates", args, value)'

ReadLogStatusEnum:
  type: enum
  config:
    values:
      READING: "reading"
      FINISHED: "finished"
      TBR: "tbr"
      DNF: "dnf"

ReadLogSortableFieldsEnum:
  type: enum
  config:
    values:
      CREATED_AT: 'createdAt'
      UPDATED_AT: 'updatedAt'
      FINISHED_AT: 'finishedAt'
      RATING: 'rating'

ReadLogPageUpdateSortableFieldsEnum:
  type: enum
  config:
    values:
      CREATED_AT: 'createdAt'

CreateReadLogInput:
  type: input-object
  config:
    fields:
      currentPage: "Int"
      status: "ReadLogStatusEnum!"

ReadLogPageUpdate:
  type: object
  config:
    fields:
      id: "Int!"
      log: "ReadLog!"
      fromPage: "Int!"
      toPage: "Int!"
      createdAt: "DateTimeImmutable!"

CreateReadLogPageUpdateInput:
  type: input-object
  config:
    fields:
      logId: "Int!"
      toPage: "Int!"
