User:
  type: object
  config:
    fields:
      id: "Int!"
      username: "String!"
      bio: "String"
      profilePicture:
        type: "String!"
        resolve: '@=query("App\\GraphQL\\Resolver\\UserResolver::resolveProfilePicture", value)'
      followers:
        type: "FollowList!"
        args:
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\FollowResolver::followers", args, value)'
      following:
        type: "FollowList!"
        args:
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\FollowResolver::following", args, value)'
      followedByMe:
        type: "Boolean"
        resolve: '@=query("App\\GraphQL\\Resolver\\FollowResolver::resolveFollowedByMe", value)'
      readLogs:
        type: "[ReadLog]!"
        args:
          statuses: "[ReadLogStatusEnum!]"
          limit: "Int"
          offset: "Int"
          sortField: "ReadLogSortableFieldsEnum"
          sortDirection: "SortDirectionEnum"
        resolve: '@=query("App\\GraphQL\\Resolver\\ReadLogResolver::userReadLogs", args, value)'
      currentRead:
        type: "ReadLog"
        resolve: '@=query("App\\GraphQL\\Resolver\\ReadLogResolver::resolveUserCurrentRead", value)'
      posts:
        type: "[FeedPost]!"
        args:
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\UserResolver::resolveUserPosts", args, value)'

Me:
  type: object
  inherits: [User]
  config:
    fields:
      email: "String!"
