User:
  type: object
  config:
    fields:
      id: "Int!"
      username: "String!"
      profilePicture:
        type: "String!"
        resolve: '@=query("App\\GraphQL\\Resolver\\UserResolver::resolveProfilePicture", value)'
      followers:
        type: "FollowList!"
        args:
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\FollowResolver::followers", args, value)'
      following:
        type: "FollowList!"
        args:
          limit: "Int"
          offset: "Int"
        resolve: '@=query("App\\GraphQL\\Resolver\\FollowResolver::following", args, value)'
      readLogs:
        type: "[ReadLog]!"
        args:
          statuses: "[ReadLogStatusEnum!]"
          limit: "Int"
          offset: "Int"
          sortField: "ReadLogSortableFieldsEnum"
          sortDirection: "SortDirectionEnum"
        resolve: '@=query("App\\GraphQL\\Resolver\\ReadLogResolver::userReadLogs", args, value)'

Me:
  type: object
  inherits: [User]
  config:
    fields:
      email: "String!"
